config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :preprocessor
  resources :postprocessor
  patch 'calculate', action: :calculate, controller: 'processor'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/construction.rb
# frozen_string_literal: true

class Construction < ApplicationRecord
  has_many :rods, dependent: :destroy

  validates_presence_of :name

  accepts_nested_attributes_for :rods
end

app/models/rod.rb
# frozen_string_literal: true

class Rod < ApplicationRecord
  belongs_to :construction
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/postprocessor_controller.rb
# frozen_string_literal: true

class PostprocessorController < ApplicationController
  before_action :set_construction!, only: %i[show]
  before_action :set_rods!, only: %i[show]

  def index
    @constructions = Construction.all
  end

  def show; end

  private

  def set_construction!
    @construction = Construction.find(params[:id])
  end

  def set_rods!
    @rods = @construction.rods
  end
end

app/controllers/preprocessor_controller.rb
#frozen_string_literal: true

class PreprocessorController < ApplicationController
  before_action :set_construction!, only: %i[show update edit destroy]
  before_action :set_rods!, only: %i[show edit]
  after_action :processor_calculate, only: %i[update create]

  def index
    @constructions = Construction.all
  end

  def show; end

  def edit; end

  def update
    ActiveRecord::Base.transaction do
      @construction.rods.destroy_all
      @construction.update!(construction_params)
      rods = JSON.parse(params[:construction][:rods])
      created_rods = rods.each_with_object([]) do |rod, cr_rods|
        cr_rods << Rod.create(
          place_id: rod['place_id'],
          l: rod['l'].to_i,
          a: rod['a'].to_i,
          e: rod['e'].to_i,
          b: rod['b'].to_i,
          f: rod['f'].to_i,
          q: rod['q'].to_i
        )
      end
      @construction.update!(
        rods: created_rods
      )
    end
  end

  def new
    @construction = Construction.new
  end

  def create
    @construction = Construction.create(construction_params)
    rods = JSON.parse(params[:construction][:rods])
    created_rods = rods.each_with_object([]) do |rod, cr_rods|
      cr_rods << Rod.create(
           place_id: rod['place_id'].to_i,
           l: rod['l'].to_i,
           a: rod['a'].to_i,
           e: rod['e'].to_i,
           b: rod['b'].to_i,
           f: rod['f'].to_i,
           q: rod['q'].to_i
         )
    end
    @construction.update!(
      rods: created_rods
    )
    redirect_to preprocessor_index_path
  end

  def destroy
    @construction.destroy!
    redirect_to preprocessor_index_path
  end

  private

  def set_construction!
    @construction = Construction.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to preprocessor_index_path
  end

  def set_rods!
    @rods = @construction.rods
  end

  def construction_params
    params.require(:construction).permit(:name, :left_support, :right_support, rods: [:place_id, :l, :a, :e, :b, :f, :q])
  end

  def processor_calculate
    ConstructionService.perform(@construction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def self.all_constructions
    Construction.all
  end
end

app/views/home/index.html.erb
<div class="container-sm mt-4">
  <ul class="list-group d-flex justify-content-between flex-column ">
    <%= link_to "Препроцессор", preprocessor_index_path, class: "list-group-item d-flex justify-content-center" %>
    <%= link_to "Построцессор", postprocessor_index_path, class: "list-group-item d-flex justify-content-center" %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaprRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: 'shared/header' %>
      <div class="container-fluid bg-light">
        <%= yield %>
      </div>
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/postprocessor/_construction_list.html.erb
<div id="constructions-list">
  <ul class="list-group">
    <% @constructions.each do |constr| %>
      <li class="list-group-item d-flex justify-content-center align-items-center">
        <%= link_to constr.name, postprocessor_path(constr), class: "list-group-item-action link-primary mb-2 mt-2"%>
      </li>
    <% end %>
  </ul>
</div>

app/views/postprocessor/_graphic.html.erb
<div class="figure">
  <figure class="highcharts-figure" data-controller="graphic-controller">
    <div id="container"></div>
  </figure>
</div>

app/views/postprocessor/_table.html.erb
<div class="card mb-2" id="construction-table"
     <%= tag.attributes( 'data-edit-construction-table-id-value': @construction.id) %>>
  <div class="card-header"
       id="construction-title">
    <%= @construction.name %>
  </div>
  <% @rods.sort_by { |r| r.place_id  }.each do |rod| %>
    <div class="card-body">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Стержень <%= rod.place_id %></th>
          <% x = rod.l / 10 %>
          <% rod.n.size.times do |i| %>
            <th><%= (x * i).round(2) %></th>
          <% end %>
        </tr>
        </thead>
        <tbody>
            <tr>
              <td>N</td>
              <% rod.n.size.times do |i| %>
                <td><%= rod.n[i].round(2) %></td>
              <% end %>
            </tr>
            <tr>
              <td>U</td>
              <% rod.u.size.times do |i| %>
                <td><%= rod.u[i].round(2) %></td>
              <% end %>
            </tr>
            <tr>
              <td><%= 963.chr  %></td>
              <% rod.s.size.times do |i| %>
                <td class="<%= rod.s[i] <= rod.b && rod.s[i] >= -rod.b ? "text-success" : "text-danger" %>"><%= rod.s[i].round(2) %></td>
              <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/postprocessor/index.html.erb
<div class="container mt-4">
  <%= render partial: 'postprocessor/construction_list' %>
</div>

app/views/postprocessor/show.html.erb
<div class="container mt-4">
  <%= render "postprocessor/table" %>

  <%#= render partial: "postprocessor/graphic" %>
</div>

app/views/preprocessor/_constructions_list.html.erb
<div id="constructions-list">
  <ul class="list-group">
    <% @constructions.each do |constr| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to constr.name, edit_preprocessor_path(constr), class: "list-group-item-action link-primary"%>
        <%= button_to 'Удалить', preprocessor_path(constr), method: :delete, confirm: 'Вы уверены?', class: "btn btn-outline-danger"%>
      </li>
    <% end %>
  </ul>
</div>

app/views/preprocessor/_form.html.erb
<div class="card" id="construction-table" data-controller="new-construction-table">
  <div class="card-header" id="construction-title" data-action="click->new-construction-table#editTitle">
    New
  </div>
  <div class="card-body">
    <table class="table table-hover">
      <thead>
      <tr>
        <th scope="col">№</th>
        <th scope="col">Длина стержня (L)</th>
        <th scope="col">Площадь поперечного сечения (A)</th>
        <th scope="col">Модуль упругости (E)</th>
        <th scope="col">Допускаемое напряжение (<%= 963.chr %>)</th>
        <th scope="col">Сосредоточенная нагрузка (F)</th>
        <th scope="col">Погонная нагрузка (Q)</th>
      </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td data-action="click->new-construction-table#editCell">0</td>
          <td data-action="click->new-construction-table#editCell">0</td>
          <td data-action="click->new-construction-table#editCell">0</td>
          <td data-action="click->new-construction-table#editCell">0</td>
          <td data-action="click->new-construction-table#editCell">0</td>
          <td data-action="click->new-construction-table#editCell">0</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/preprocessor/_table.html.erb
<div class="card mb-2" id="construction-table" data-controller="edit-construction-table"
     <%= tag.attributes( 'data-edit-construction-table-id-value': @construction.id) %>>
  <div class="card-header"
       data-action="click->edit-construction-table#editTitle"
       data-search-target="title"
       id="construction-title">
    <%= @construction.name %>
  </div>
  <div class="card-body">
    <table class="table table-hover">
      <thead>
      <tr>
        <th scope="col">№</th>
        <th scope="col">Длина стержня (L)</th>
        <th scope="col">Площадь поперечного сечения (A)</th>
        <th scope="col">Модуль упругости (E)</th>
        <th scope="col">Допускаемое напряжение (<%= 963.chr %>)</th>
        <th scope="col">Сосредоточенная нагрузка (F)</th>
        <th scope="col">Погонная нагрузка (Q)</th>
      </tr>
      </thead>
      <tbody>
      <% @rods.sort_by { |r| r.place_id  }.each do |rod| %>
        <tr data-search-target="constructRow">
          <td><%= rod.place_id %></td>
          <td data-action="click->edit-construction-table#editCell"><%= rod.l %></td>
          <td data-action="click->edit-construction-table#editCell"><%= rod.a %></td>
          <td data-action="click->edit-construction-table#editCell"><%= rod.e %></td>
          <td data-action="click->edit-construction-table#editCell"><%= rod.b %></td>
          <td data-action="click->edit-construction-table#editCell"><%= rod.f %></td>
          <td data-action="click->edit-construction-table#editCell"><%= rod.q %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/preprocessor/_visualizer.html.erb
<div class="card">
  <img
    id='supportLeft'
    src="/assets/supportLeft.png"
    style="display: none"
  />
  <img
    id='supportRight'
    src="/assets/supportRight.png"
    style="display: none"
  />
  <img
    id='arrowLeft'
    src="/assets/arrowLeft.png"
    style="display: none"
  />
  <img
    id='arrowRight'
    src="/assets/arrowRight.png"
    style="display: none"
  />
  <img
    id='arrowLongLeft'
    src="/assets/arrowLongLeft.png"
    style="display: none"
  />
  <img
    id='arrowLongRight'
    src="/assets/arrowLongRight.png"
    style="display: none"
  />
  <canvas id="visualizer"></canvas>
</div>

app/views/preprocessor/edit.html.erb
<div class="container mt-4">
  <div class="d-flex justify-content-center">
    <div class="d-flex justify-content-evenly mb-2 mt-2" data-controller="edit-construction-table">
      <button type="button" class="btn btn-outline-success me-4" data-action="click->edit-construction-table#addRow">
        Добавить стержень
      </button>
      <button type="button" class="btn btn-outline-danger me-4" data-action="click->edit-construction-table#deleteRow">
        Удалить стержень
      </button>
      <div class="form-check me-4">
        <% if @construction.left_support %>
          <input class="form-check-input" type="checkbox" id="support-left" data-search-target="supportLeft" checked>
        <% else %>
          <input class="form-check-input" type="checkbox" id="support-left" data-search-target="supportLeft">
        <% end %>
        <label class="form-check-label" for="support-left">
          Опора слева
        </label>
      </div>
      <div class="form-check">
        <% if @construction.right_support %>
          <input class="form-check-input" type="checkbox" id="support-right" data-search-target="supportRight" checked>
        <% else %>
          <input class="form-check-input" type="checkbox" id="support-right" data-search-target="supportRight">
        <% end %>
        <label class="form-check-label" for="support-right">
          Опора справа
        </label>
      </div>
    </div>
  </div>
  <%= render partial: 'preprocessor/table' %>
  <div class="d-flex justify-content-center">
    <div data-controller="edit-construction-table">
      <button type="button" class="btn btn-primary me-2" data-action="click->edit-construction-table#saveEdited">Сохранить</button>
    </div>
    <div data-controller="visualizer">
      <button type="button" class="btn btn-info" data-action="click->visualizer#draw">Отрисовка</button>
    </div>
  </div>
  <%= render partial: 'preprocessor/visualizer' %>
</div>

app/views/preprocessor/index.html.erb
<div class="container mt-4">
  <%= render partial: 'preprocessor/constructions_list' %>
  <div class="d-flex justify-content-center mt-2">
    <%= link_to "Добавить новую конструкцию", new_preprocessor_path, class:  "btn btn-primary" %>
  </div>
</div>

app/views/preprocessor/new.html.erb
<div class="container mt-4">
  <div class="d-flex justify-content-center">
    <div class="d-flex justify-content-evenly mb-2 mt-2" data-controller="new-construction-table">
      <button type="button" class="btn btn-outline-success me-4" data-action="click->new-construction-table#addRow">
        Добавить стержень
      </button>
      <button type="button" class="btn btn-outline-danger me-4" data-action="click->new-construction-table#deleteRow">
        Удалить стержень
      </button>
      <div class="form-check me-4">
        <input class="form-check-input" type="checkbox" id="support-left" data-search-target="supportLeft">
        <label class="form-check-label" for="support-left">
          Опора слева
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="support-right" data-search-target="supportRight">
        <label class="form-check-label" for="support-right">
          Опора справа
        </label>
      </div>
    </div>
  </div>
  <%= render 'preprocessor/form' %>
  <div class="d-flex justify-content-center">
    <div data-controller="new-construction-table">
      <button type="button" class="btn btn-primary me-2" data-action="click->new-construction-table#saveEdited">Сохранить</button>
    </div>
    <div data-controller="visualizer">
      <button type="button" class="btn btn-info" data-action="click->visualizer#draw">Отрисовка</button>
    </div>
  </div>
  <%= render partial: 'preprocessor/visualizer' %>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-center text-bg-light fixed-bottom">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    <h7 class="text-white">© 2022 Copyright:</h7>
    <a class="text-light" href="https://github.com/Keallar">Keallar</a>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "CАПР", root_path, class: "navbar-brand" %>
    <div class="container">
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <%= link_to "Препроцессор", preprocessor_index_path, class: "nav-link link-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "Постпроцессор", postprocessor_index_path, class: "nav-link link-light" %>
        </li>
      </ul>
    </div>
    <div class="btn-group dropstart">
      <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Конструкции
      </button>
      <ul class="dropdown-menu dropdown-menu-dark">
        <% ApplicationHelper.all_constructions.each do |constr| %>
          <%= link_to constr.name, edit_preprocessor_path(constr), class: "dropdown-item"%>
        <% end %>
      </ul>
    </div>
  </div>
</nav>